# Generated by Django 4.1.5 on 2023-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quetions',
            name='image',
        ),
        migrations.AddField(
            model_name='quetions',
            name='photo',
            field=models.CharField(max_length=300, null=True, verbose_name='Rasm file_id'),
        ),
    ]
