# Generated by Django 4.1.5 on 2023-01-08 04:02

import appp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appp', '0002_remove_quetions_image_quetions_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='call_back',
            field=models.CharField(blank=True, default=appp.models.create_new_ref_number, max_length=10, unique=True),
        ),
    ]
